### ISSUE TITLE
Dynamic Surroundings causing minor incompatibility with C2ME

### ISSUE THREAD

**Issue by vincentix** [OreCruncher/DynamicSurroundingsFabric#89] opened 2024-02-17 03:42 UTC
Causes an error but unknown what effect it has on either mod. Stacktrace as follows. 

```
This is usually NOT a bug in C2ME, but a bug in another mod or in vanilla code. 
Possible solutions: 
  - Find possible causes in the stack trace below and 
    - if caused by another mod, report this to the corresponding mod authors 
    - if no other mods are involved, report this to C2ME 
java.util.ConcurrentModificationException: ThreadLocalRandom accessed from a different thread (owner: Render thread, current: Sound engine)
	at com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.handleNotOwner(CheckedThreadLocalRandom.java:55) ~[c2me-fixes-worldgen-threading-is+alpha.11.5-9d70c476c16a4c1b.jar:?]
	at com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.isSafe(CheckedThreadLocalRandom.java:38) ~[c2me-fixes-worldgen-threading-is+alpha.11.5-9d70c476c16a4c1b.jar:?]
	at com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.method_43156(CheckedThreadLocalRandom.java:86) ~[c2me-fixes-worldgen-threading-is+alpha.11.5-9d70c476c16a4c1b.jar:?]
	at net.minecraft.class_6566.method_43048(class_6566.java:33) ~[client-intermediary.jar:?]
	at net.minecraft.class_1146.method_4887(class_1146.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.class_1102.method_4783(net/minecraft/class_1102.java:50) ~[client-intermediary.jar:?]
	at org.orecruncher.dsurround.sound.SoundInstanceHandler.inRange(SoundInstanceHandler.java:114) ~[DynamicSurroundings-Fabric-1.20.1-0.3.2.jar:?]
	at org.orecruncher.dsurround.sound.SoundInstanceHandler.inRange(SoundInstanceHandler.java:128) ~[DynamicSurroundings-Fabric-1.20.1-0.3.2.jar:?]
	at org.orecruncher.dsurround.runtime.audio.SoundFXUtils.calculate(SoundFXUtils.java:114) ~[DynamicSurroundings-Fabric-1.20.1-0.3.2.jar:?]
	at org.orecruncher.dsurround.runtime.audio.SourceContext.updateImpl(SourceContext.java:166) ~[DynamicSurroundings-Fabric-1.20.1-0.3.2.jar:?]
	at org.orecruncher.dsurround.runtime.audio.SourceContext.exec(SourceContext.java:158) ~[DynamicSurroundings-Fabric-1.20.1-0.3.2.jar:?]
	at org.orecruncher.dsurround.runtime.audio.SoundFXProcessor.lambda$onSourcePlay$1(SoundFXProcessor.java:146) ~[DynamicSurroundings-Fabric-1.20.1-0.3.2.jar:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at org.orecruncher.dsurround.runtime.audio.SoundFXProcessor.onSourcePlay(SoundFXProcessor.java:144) ~[DynamicSurroundings-Fabric-1.20.1-0.3.2.jar:?]
	at net.minecraft.class_4224.handler$beb000$dsurround$onSourcePlay(org/orecruncher/dsurround/mixins/audio/MixinSource.java [dsurround.mixins.json]:53) ~[client-intermediary.jar:?]
	at net.minecraft.class_4224.method_19650(class_4224.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_1140.method_19752(net/minecraft/class_1140.java:461) ~[client-intermediary.jar:?]
	at net.minecraft.class_4235$class_4236.method_19737(net/minecraft/class_4235$class_4236.java:34) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(net/minecraft/class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(net/minecraft/class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(net/minecraft/class_1255.java:139) ~[client-intermediary.jar:?]
	at net.minecraft.class_4238.method_19765(class_4238.java:42) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21:38:14] [pool-7-thread-2/ERROR]: ThreadLocalRandom accessed from a different thread (owner: Render thread, current: pool-7-thread-2)
```

**Comment by OreCruncher** [comment] 2024-02-17 03:52
Dupe of [#87]

**Closed by OreCruncher** 2024-02-17 03:52 UTC
