### ISSUE TITLE
Crash at world load

### ISSUE THREAD

**Issue by vivagabe** [OreCruncher/DynamicSurroundingsFabric#101] opened 2024-03-25 03:26 UTC
Using forge 1.20.1 with sinytra connector. hopefully an easy fix.

[crash-2024-03-24_20.25.39-client.txt](https://github.com/OreCruncher/DynamicSurroundingsFabric/files/14738436/crash-2024-03-24_20.25.39-client.txt)

**Comment by OreCruncher** [comment] 2024-03-25 12:32
Dupe of #98 ?

**Comment by OreCruncher** [comment] 2024-03-28 12:04
Closing as duplicate.

**Closed by OreCruncher** 2024-03-28 12:04 UTC
